import { Router } from "express";
import * as authController from "../controllers/auth.controller.js";
import * as userController from "../controllers/user.controller.js";
import * as serviceController from "../controllers/service.controller.js";
import * as barberController from "../controllers/barber.controller.js";
import * as scheduleController from "../controllers/schedule.controller.js";
import * as appointmentController from "../controllers/appointment.controller.js";
import * as adminController from "../controllers/admin.controller.js";
import { auth, roles } from "../middleware/auth.js";
import { asyncHandler } from "../utils/api.js";

const router = Router();
const wrap = (controller) => asyncHandler(controller);
router.post("/auth/register", wrap(authController.register));
router.post("/auth/login", wrap(authController.login));
router.get("/auth/me", auth, wrap(authController.me));
router.patch("/auth/change-password", auth, wrap(authController.changePassword));
router.get("/users/me", auth, wrap(authController.me));
router.patch("/users/me", auth, wrap(userController.updateMe));
router.get("/users", auth, roles("ADMIN"), wrap(userController.listUsers));
router.post("/users", auth, roles("ADMIN"), wrap(userController.createUser));
router.get("/users/:id", auth, roles("ADMIN"), wrap(userController.getUser));
router.put("/users/:id", auth, roles("ADMIN"), wrap(userController.updateUser));
router.patch("/users/:id/status", auth, roles("ADMIN"), wrap(userController.setStatus));
router.patch("/users/:id/role", auth, roles("ADMIN"), wrap(userController.setRole));
router.delete("/users/:id", auth, roles("ADMIN"), wrap(userController.removeUser));
router.get("/services", wrap(serviceController.listServices));
router.get("/services/:id", wrap(serviceController.getService));
router.post("/services", auth, roles("ADMIN"), wrap(serviceController.createService));
router.put("/services/:id", auth, roles("ADMIN"), wrap(serviceController.updateService));
router.patch("/services/:id/status", auth, roles("ADMIN"), wrap(serviceController.setServiceStatus));
router.delete("/services/:id", auth, roles("ADMIN"), wrap(serviceController.removeService));
router.get("/barbers", wrap(barberController.listBarbers));
router.get("/barbers/:id/services", wrap(barberController.getBarberServices));
router.get("/barbers/:id/availability", wrap(barberController.getBarberAvailability));
router.get("/barbers/:barberId/schedules", wrap(barberController.getBarberSchedules));
router.get("/barbers/:id", wrap(barberController.getBarber));
router.post("/barbers", auth, roles("ADMIN"), wrap(barberController.createBarber));
router.put("/barbers/:id", auth, roles("ADMIN"), wrap(barberController.updateBarber));
router.patch("/barbers/:id/status", auth, roles("ADMIN"), wrap(barberController.setBarberStatus));
router.patch("/barbers/:id/services", auth, roles("ADMIN"), wrap(barberController.setBarberServices));
router.delete("/barbers/:id", auth, roles("ADMIN"), wrap(barberController.removeBarber));
router.get("/schedules", auth, roles("ADMIN"), wrap(scheduleController.listSchedules));
router.get("/schedules/:id", auth, roles("ADMIN"), wrap(scheduleController.getSchedule));
router.post("/schedules", auth, roles("ADMIN"), wrap(scheduleController.createSchedule));
router.put("/schedules/:id", auth, roles("ADMIN"), wrap(scheduleController.updateSchedule));
router.patch("/schedules/:id/status", auth, roles("ADMIN"), wrap(scheduleController.setScheduleStatus));
router.delete("/schedules/:id", auth, roles("ADMIN"), wrap(scheduleController.removeSchedule));
router.put("/barbers/:barberId/schedules/:dayOfWeek", auth, roles("ADMIN"), wrap(scheduleController.upsertBarberSchedule));
router.get("/availability", wrap(scheduleController.availability));
router.post("/appointments", auth, roles("CLIENT", "ADMIN"), wrap(appointmentController.createAppointment));
router.get("/appointments/my-appointments", auth, roles("CLIENT"), wrap(appointmentController.myAppointments));
router.patch("/appointments/:id/cancel", auth, wrap(appointmentController.cancelAppointment));
router.get("/appointments/:id", auth, wrap(appointmentController.getAppointment));
router.get("/barber/appointments", auth, roles("BARBER"), wrap(appointmentController.barberAppointments));
router.patch("/barber/appointments/:id/approve", auth, roles("BARBER", "ADMIN"), wrap(appointmentController.approve));
router.patch("/barber/appointments/:id/reject", auth, roles("BARBER", "ADMIN"), wrap(appointmentController.reject));
router.patch("/barber/appointments/:id/complete", auth, roles("BARBER", "ADMIN"), wrap(appointmentController.complete));
router.patch("/barber/appointments/:id/no-show", auth, roles("BARBER", "ADMIN"), wrap(appointmentController.noShow));
router.get("/admin/appointments", auth, roles("ADMIN"), wrap(appointmentController.adminAppointments));
router.get("/admin/appointments/:id", auth, roles("ADMIN"), wrap(appointmentController.adminGetAppointment));
router.patch("/admin/appointments/:id/reassign", auth, roles("ADMIN"), wrap(appointmentController.reassign));
router.patch("/admin/appointments/:id/status", auth, roles("ADMIN"), wrap(appointmentController.adminStatus));
router.patch("/admin/appointments/:id/cancel", auth, roles("ADMIN"), wrap(appointmentController.cancelAppointment));
router.get("/audit-logs", auth, roles("ADMIN"), wrap(adminController.auditLogs));
router.get("/audit-logs/user/:userId", auth, roles("ADMIN"), wrap(adminController.userAuditLogs));
router.get("/audit-logs/:id", auth, roles("ADMIN"), wrap(adminController.auditLog));
router.get("/dashboard/summary", auth, roles("ADMIN"), wrap(adminController.dashboard));
router.get("/reports/appointments-by-status", auth, roles("ADMIN"), wrap(adminController.appointmentsByStatus));
router.get("/reports/popular-services", auth, roles("ADMIN"), wrap(adminController.popularServices));
router.get("/reports/appointments-by-barber", auth, roles("ADMIN"), wrap(adminController.appointmentsByBarber));
router.get("/reports/appointments-by-date", auth, roles("ADMIN"), wrap(adminController.appointmentsByDate));
router.get("/reports/estimated-revenue", auth, roles("ADMIN"), wrap(adminController.estimatedRevenue));
export default router;
